config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archives/index'
  get 'home/about'
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :category
  validates :calories, :protiens, :carbohydrates, :fats, :meal_type, :category_id, presence:  true

  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :protiens, :fats, :carbohydrates, :category_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered"> Entries for <%= day %>
      </h3>

      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Calories</p>
            <p class="title"><%= entries.pluck(:calories).sum %></p>
          </div>
        </div>

        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Protiens</p>
            <p class="title"><%= entries.pluck(:protiens).sum %>g</p>
          </div>
        </div>

        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
          </div>
        </div>

        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum %>g</p>
          </div>
        </div>
      </nav>



      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> calories,
              <%= entry.protiens %>g protein,
              <%= entry.carbohydrates %>g carbs,
              <%= entry.fats %>g fat
            </div>
          </div>
          <br>
        <% end %>
      <% end %>


    <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/entries/_entry.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"> Meal </p>
        <p class="subtitle is-6"><%= entry.meal_type %>; <%= entry.category.title %></p>
      </div>
  </div>

  <div class="content">
    <div id="<%= dom_id entry %>">


      <p>
        <strong>Calories:</strong>
        <%= entry.calories %>
      </p>

      <p>
        <strong>Protiens:</strong>
        <%= entry.protiens %>
      </p>

      <p>
        <strong>carbohydrates:</strong>
        <%= entry.carbohydrates %>
      </p>

      <p>
        <strong>Fats:</strong>
        <%= entry.fats %>
      </p>
      <time datetime="2016-1-1" class="italic"> Logged <%= time_ago_in_words(entry.created_at) %> ago</time>
    </div>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="mesage is-danger">
      <div class="message-header"></div>
        <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal, class:"label", style: "display: block" %>
    <div class="control">
      <%= form.text_field :meal_type, class:"input", type:"text"%>
    </div>
  </div>

  <div class="field">
    <%= form.label :calories, class:"label", style: "display: block" %>
    <div class="control">
      <%= form.number_field :calories, class:"input", type:"number"%>
    </div>
  </div>


  <div class="field">
    <%= form.label :protiens, class:"label", style: "display: block" %>
    <div class="control">
      <%= form.number_field :protiens, class:"input", type:"number"%>
    </div>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class:"label", style: "display: block" %>
    <div class="control">
      <%= form.number_field :carbohydrates, class:"input", type:"number"%>
    </div>
  </div>

  <div class="field">
    <%= form.label :fats, class:"label", style: "display: block" %>
    <div class="control">
      <%= form.number_field :fats, class:"input", type:"number"%>
    </div>
  </div>

  <div class="field">
    <%= form.label :category, class:"label", style: "display: block" %>
    <div class="select">
      <%= form.select :category_id, Category.all.collect {|u| [u.title, u.id]}%>
    </div>
  </div>

  <br>
  <div class="buttons">
    <%= form.submit class:"button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3"> Editing entry</h1>

    <%= render "form", entry: @entry %>

    <br>

    <div class="buttons">
      <%= link_to "Show", @entry, class:"button is-primary" %>
      <%= link_to "Back", entries_path, class:"button is-link" %>
    </div>
  </div>
</div>

app/views/entries/index.html.erb
<br>


<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %>; <%= entry.category.title if entry.category.present? %></p>
        </header>
        <div class="card-content">
          <div class="content">
              <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
              <p><span class="has-text-weight-bold"><%= entry.protiens %></span> grams of protein</p>
              <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
              <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat</p>
              <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'Show', entry, class: "card-footer-item" %>
          <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
          <%# <%= button_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archives_index_path, class:"button is-link is-light " %>
</div>



<%= link_to "New entry", new_entry_path, class:"button is-link" %>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <br>
    <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>
    <%= render "form", entry: @entry %>

    <br>

    <div>
      <%= link_to "Back", entries_path, class:"button is-link"%>
    </div>
  </div>
</div>

app/views/entries/show.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <div>
      <br>
      <%= render @entry %>
    </div>
    <br>
    <div class="buttons">
      <%= link_to "Edit", edit_entry_path(@entry), class:"button is-primary"%>
      <%= link_to "Back", entries_path, class:"button is-link" %>
      <%= button_to "Destroy", @entry, method: :delete, class:"button is-danger" %>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/entries">
      <svg fill="#00b894" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><title>location-food</title><path d="M18 11v7a2 2 0 0 1-4 0v-5h-2V3a3 3 0 0 1 3-3h3v11zM4 10a2 2 0 0 1-2-2V1a1 1 0 0 1 2 0v4h1V1a1 1 0 0 1 2 0v4h1V1a1 1 0 0 1 2 0v7a2 2 0 0 1-2 2v8a2 2 0 0 1-4 0v-8z"></path></svg>
      <span class="has-text-weight-bold is-size-4 ml-4" style="color: #00b894">Foodlog</span>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%# <a class="navbar-item">
        Home
      </a> %>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="/home/about">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>
<%# <p>Find me in app/views/home/about.html.erb</p> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# bulma tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

  </head>

  <body >
    <%# header %>
    <%= render 'home/header' %>

    <%# notice %>
    <% if notice.present?%>
      <div class="notification is-primary is-light">
        <button class="delete"></button>
        <%= notice %>
      </div>
    <% end %>

    <%# alert %>
    <% if alert.present?%>
      <div class="notification is-danger is-light">
        <button class="delete"></button>
        <%= alert %>
      </div>
    <% end %>


    <div class="container">
      <%= yield %>
    </div>

  </body>
  <%# <%= render 'home/footer' %>
</html>